stages:
  - analyze
  - test
  - build
  - archive

Analyze macOS:
  stage: analyze
  script:
    - xcodebuild clean analyze -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Debug | xcpretty -f `xcpretty-travis-formatter`
  tags:
    - Xcode
    - macOS

Tests macOS:
  stage: test
  script:
    - xcodebuild test -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Debug -enableCodeCoverage YES | xcpretty --test --tap --report html
    - slather coverage --scheme 'Computational Physics' --show ComputationalPhysics.xcodeproj
  tags:
    - Xcode
    - macOS

Build macOS:
  stage: build
  script:
    - xcodebuild clean build -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Release | xcpretty -f `xcpretty-travis-formatter`
  tags:
    - Xcode
    - macOS

Build Linux:
  stage: build
  image: ubuntu:bionic
  before_script:
    - apt-get update
    - apt-get install -y cmake gcc g++ freeglut3-dev
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
  tags:
    - docker

Archive macOS:
  stage: archive
  script:
    - xcodebuild archive -archivePath build/ComputationalPhysics -scheme 'Computational Physics' -configuration Release | xcpretty -f `xcpretty-travis-formatter`
  only:
    - master
  artifacts:
    paths:
    - build/ComputationalPhysics.xcarchive
  tags:
    - Xcode
    - macOS
