laguage: cpp

stages:
  - Build
  - Test

jobs:
  include:
    - stage: Build
      name: "Build macOS"
      os: osx
      osx_image: xcode10.1
      script: xcodebuild clean build -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Release | xcpretty -f `xcpretty-travis-formatter`
    - stage: Build
      name: "Build Xenial"
      os: linux
      dist: xenial
      before_install: sudo apt-get update
      install: sudo apt-get install -y freeglut3-dev
      script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
    - stage: Test
      name: "Unit Tests macOS"
      os: osx
      osx_image: xcode10.1
      script: xcodebuild test -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Debug -enableCodeCoverage YES | xcpretty --test --tap --report html
