laguage: cpp

matrix:
  include:
    - dist: xenial
    - os: osx
      osx_image: xcode10.1
      xcode_project: ComputationalPhysics.xcodeproj
      xcode_scheme: Computational Physics

addons:
  apt:
    packages:
    - cmake
    - gcc
    - g++
    - freeglut3-dev
    update: true

stages:
  - Build
  - Test

jobs:
  include:
    - stage: "Build"
      name: "Build macOS"
      os: osx
      script: xcodebuild clean build -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Release | xcpretty -f `xcpretty-travis-formatter`
    - stage: "Build"
      name: "Build Xenial"
      os: xenial
      script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
    - stage: "Test"
      name: "Unit Tests macOS"
      os: osx
      script: xcodebuild test -project ComputationalPhysics.xcodeproj -scheme 'Computational Physics' -configuration Debug -enableCodeCoverage YES | xcpretty --test --tap --report html
