version: 2
jobs:
  build:
    docker:
      - image: "ubuntu:xenial-20181218"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install -y gcc g++ make cmake
      - run:
          name: Create Build Files
          command: cmake -DCMAKE_BUILD_TYPE=Release .
      - run:
          name: Build Executable
          command: make
      - store_artifacts:
          # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: bin/ComputationalPhysics
          destination: artifacts
